implemented CLI parser and added logic to use xmlPath from CLI
IgnacioCarol/TpTaller1 pull request #17
Opened 2020-10-31 14:13 UTC by d-bizari

2020-10-31 19:31 UTC, danielacarrero requested changes

2020-10-31 19:31 UTC, danielacarrero commented on config.xml
> +<configuracion>
En la carpeta resources ya hay un config.xml, podríamos poner este allí y reemplazar el que ya está que era solo el ejemplo que pusieron en el enunciado

2020-10-31 19:31 UTC, danielacarrero commented on src/main.cpp
> +        *xmlPath = "./test/resources/config_test.xml"; // set default xml
Este no sería el default.. pondría de alguna manera que si el xmlPath no está definido, ponga el default que lo define directamente Config, sin poner ningún path, te parece?

2020-10-31 19:31 UTC, danielacarrero commented on src/main.cpp
> +    Logger::getInstance()->info(xmlPath);
```suggestion
    Logger::getInstance()->info("XML Path: " + xmlPath);
```

2020-10-31 19:34 UTC, danielacarrero commented on config.xml
> +                <numero>2</numero>
Podríamos aprovechar de poner la config de los 3 niveles

2020-11-02 23:53 UTC, d-bizari commented on config.xml
> +<configuracion>
Sip, no lo habia visto, tomo ese

2020-11-02 23:57 UTC, d-bizari commented on src/main.cpp
> +        *xmlPath = "./test/resources/config_test.xml"; // set default xml
mmmmmmmm no se, lo pense en el momento que lo estaba codeando, pero como es la parte del CLI lo pense como que si no me mandan uno uso un XML por defecto. Y que el default de las configs sea un plan de contigencia por si falla el parseo o falta algun campo. Ademas es mas comodo para ir haciendo pruebas ir modificando el XML. No se que te parece ?

2020-11-03 00:02 UTC, d-bizari commented on config.xml
> +                <numero>2</numero>
Diria de verlo en un nuevo branch con todos los cambios ya cargados

2020-11-03 03:50 UTC, danielacarrero commented on config.xml
> +                <numero>2</numero>
lo agregué en mi PR con el 3er stage

2020-11-03 03:52 UTC, danielacarrero commented on src/main.cpp
> +        *xmlPath = "./test/resources/config_test.xml"; // set default xml
Claro, pero el XML por defecto es el que está en Config con constantes, justo para que no dependa de ningún file en caso de que no existan. Igual no hay problema, si falla este, se va a poner el default que decía

2020-11-03 17:42 UTC, d-bizari commented on config.xml
> +                <numero>2</numero>
joya

2020-11-03 17:43 UTC, d-bizari commented on src/main.cpp
> +        *xmlPath = "./test/resources/config_test.xml"; // set default xml
Exacto, por eso! Lo marco entonces como resuelto. Si te parece marcalo como approve y lo mergeamos

2020-11-23 20:07 UTC, Mivircruz commented on src/main.cpp
> +typedef enum {SERVER, CLIENT} game_mode_t;
No convendría tener un archivo que sea types.c y definir todos los enums/constantes ahí? Igual es algo que no afecta nada por ahora, era un comentario nomas

2020-11-23 20:07 UTC, Mivircruz commented on src/main.cpp
> +    int result = inet_pton(AF_INET, ipAddr->c_str(), &(sa.sin_addr));
Esto creo que no va porque en la clase Socket usamos getaddrinfo para conseguir las direcciones que matchean el server y el puerto y recibe las strings como vienen

2020-11-23 20:10 UTC, d-bizari commented on src/main.cpp
> +    int result = inet_pton(AF_INET, ipAddr->c_str(), &(sa.sin_addr));
Eso es para verificar que lo que mandaron sea una IP en formato valido y no un string que diga "sarsasa"

2020-11-23 20:11 UTC, d-bizari commented on src/main.cpp
> +typedef enum {SERVER, CLIENT} game_mode_t;
Podría ser, si se llegara a reutilizar tendría sentido, por el momento si solo se usa en el main para el parse no veo una mejora en pasarlo a otro lado

2020-11-23 20:15 UTC, Mivircruz commented on src/main.cpp
> +    int result = inet_pton(AF_INET, ipAddr->c_str(), &(sa.sin_addr));
Ah, okis. Igual yo lo decía porque getaddrinfo también valida eso y devuelve un código de error que podemos imprimir con gai_strerror(), pero no veo mal que valide los argumentos ni bien entre

2020-11-25 14:15 UTC, Mivircruz approved these changes

2020-11-25 14:17 UTC, Mivircruz approved these changes

2020-11-25 14:17 UTC, Mivircruz approved these changes

2020-11-26 14:54 UTC, danielacarreror approved these changes

2020-11-26 14:56 UTC, danielacarrero approved these changes

2020-11-26 14:57 UTC, merged