Login refactor
IgnacioCarol/TpTaller1 pull request #40
Opened 2020-12-06 06:30 UTC by danielacarrero

2020-12-06 06:36 UTC, IgnacioCarol commented on src/Client/Client.h
> +    Login* _login;
Tratemos de no usar el _, no se cuando lo empezamos a usar pero en verdad preferiria que no (https://stackoverflow.com/questions/589535/naming-convention-for-public-and-private-variable)

2020-12-06 07:01 UTC, IgnacioCarol commented on src/Server/Server.cpp
> +    while (playerClient != nullptr && playerClient->isConnected()) {
` while (playerClient && playerClient->isConnected()) {`
creo que seria mas conveniente (tu decision, no es algo importante)

2020-12-06 07:02 UTC, IgnacioCarol commented on src/Server/Server.cpp
> +//TODO: Consultar con DaniB si se puede borrar
@dbizari Se puede borrar?

2020-12-06 07:06 UTC, IgnacioCarol commented on src/main.cpp
> +/*
Ya se puede borrar ese codigo comentado (creo)

2020-12-06 07:10 UTC, IgnacioCarol requested changes
El codigo esta bien, hay un par de mini cambios que no son demasiado importantes ni que impiden el pr, pero hay un par de casos bordes que no creo que esten contemplados (si lo estan y mi ide me falla, no seria la primera vez, por favor avisame).
Los casos son:

- Si un usuario esta loggeado (supongamos mario mario), cuando tratas de loggearte devuelta con esas mismas credenciales te deja (no deberia).
- Si ya todos los usuarios estan loggeados, cuando uno mas trata de loggearse directamente se sale del juego sin lanzar ningun mensaje de error ni nada (puede ser que querramos cerrarlo para no tener nada consumiendo innecesariamente, y lo entiendo si va por ese lado, pero en caso que no sea lo esperado entonces estaria bueno ver por que pasa).
- Si un jugador se desconecta de la pantalla de login habiendose llenado ya la sala, entonces no lo deja entrar devuelta ni usando las mismas credenciales que antes.

2020-12-06 13:32 UTC, danielacarrero commented on src/main.cpp
> +/*
Nop, lo puse porque no está hecho. Sería la parte de iniciar el juego. Hasta este momento se ve siempre la pantalla de que está esperando a los demás jugadores.

2020-12-06 13:34 UTC, danielacarrero commented on src/Server/Server.cpp
> +    while (playerClient != nullptr && playerClient->isConnected()) {
dale, ahi lo cambié

2020-12-07 03:22 UTC, IgnacioCarol approved these changes

2020-12-07 16:31 UTC, d-bizari approved these changes

2020-12-07 16:33 UTC, merged